### ISSUE TITLE
App crashses when click tabs

### ISSUE THREAD

**Issue by kr-nahid** [reyanshmishra/Rey-MusicPlayer#1]
#### Project Information

    Repository: https://github.com/reyanshmishra/Rey-MusicPlayer

#### Expected behavior

user should be able to Rearrange tab item of the libarary when click in Tabs
#### Actual behavior

when i try to Rearrange tab item of the libarary the app crashses.
#### How to reproduce
* download the app
* open it
* go to settings
* try to Rearrange tab item of the libarary
* Browser/App version: Boom - Audio Player / 3.4.41
* Operating system: android 5.1

#### Recording Of The Bug

https://www.youtube.com/watch?v=8PnBxRDRfDE

#### logcat
```
05-10 09:50:56.864 17814 17814 E AndroidRuntime: FATAL EXCEPTION: main
05-10 09:50:56.864 17814 17814 E AndroidRuntime: Process: com.reyansh.audio.audioplayer.free, PID: 17814
05-10 09:50:56.864 17814 17814 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.reyansh.audio.audioplayer.free/com.reyansh.audio.audioplayer.free.Setting.SettingActivity}: android.app.Fragment$InstantiationException: Unable to instantiate fragment com.reyansh.audio.audioplayer.free.Setting.CustomizeSectionFragment: make sure class name exists, is public, and has an empty constructor that is public
05-10 09:50:56.864 17814 17814 E AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2743)
05-10 09:50:56.864 17814 17814 E AndroidRuntime:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808)
05-10 09:50:56.864 17814 17814 E AndroidRuntime:    at android.app.ActivityThread.-wrap12(ActivityThread.java)
05-10 09:50:56.864 17814 17814 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1544)
05-10 09:50:56.864 17814 17814 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:110)
05-10 09:50:56.864 17814 17814 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:203)
05-10 09:50:56.864 17814 17814 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:6297)
05-10 09:50:56.864 17814 17814 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
05-10 09:50:56.864 17814 17814 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
05-10 09:50:56.864 17814 17814 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
05-10 09:50:56.864 17814 17814 E AndroidRuntime: Caused by: android.app.Fragment$InstantiationException: Unable to instantiate fragment com.reyansh.audio.audioplayer.free.Setting.CustomizeSectionFragment: make sure class name exists, is public, and has an empty constructor that is public
05-10 09:50:56.864 17814 17814 E AndroidRuntime:    at android.app.Fragment.instantiate(Fragment.java:629)
05-10 09:50:56.864 17814 17814 E AndroidRuntime:    at android.preference.PreferenceActivity.switchToHeaderInner(PreferenceActivity.java:1318)
05-10 09:50:56.864 17814 17814 E AndroidRuntime:    at android.preference.PreferenceActivity.switchToHeader(PreferenceActivity.java:1341)
05-10 09:50:56.864 17814 17814 E AndroidRuntime:    at android.preference.PreferenceActivity.onCreate(PreferenceActivity.java:623)
05-10 09:50:56.864 17814 17814 E AndroidRuntime:    at com.reyansh.audio.audioplayer.free.Setting.SettingActivity.onCreate(Unknown Source)
05-10 09:50:56.864 17814 17814 E AndroidRuntime:    at android.app.Activity.performCreate(Activity.java:6685)
05-10 09:50:56.864 17814 17814 E AndroidRuntime:    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
05-10 09:50:56.864 17814 17814 E AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2696)
05-10 09:50:56.864 17814 17814 E AndroidRuntime:    ... 9 more
05-10 09:50:56.864 17814 17814 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.reyansh.audio.audioplayer.free.Setting.CustomizeSectionFragment" on path: DexPathList[[zip file "/data/app/com.reyansh.audio.audioplayer.free-1/base.apk"],nativeLibraryDirectories=[/data/app/com.reyansh.audio.audioplayer.free-1/lib/arm64, /data/app/com.reyansh.audio.audioplayer.free-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
05-10 09:50:56.864 17814 17814 E AndroidRuntime:    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-10 09:50:56.864 17814 17814 E AndroidRuntime:    at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
05-10 09:50:56.864 17814 17814 E AndroidRuntime:    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05-10 09:50:56.864 17814 17814 E AndroidRuntime:    at android.app.Fragment.instantiate(Fragment.java:615)
05-10 09:50:56.864 17814 17814 E AndroidRuntime:    ... 16 more
```

**Comment by reyanshmishra** [comment]
Done.
